"""add consult description

Revision ID: 0347f3984f4e
Revises: a1b31454e0b0
Create Date: 2016-07-19 23:38:00.909175

"""

# revision identifiers, used by Alembic.
revision = '0347f3984f4e'
down_revision = 'a1b31454e0b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('description', sa.String(length=140), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultations', 'description')
    ### end Alembic commands ###
