"""added comments table

Revision ID: 6c69768c0d86
Revises: 0347f3984f4e
Create Date: 2016-07-21 15:22:11.955507

"""

# revision identifiers, used by Alembic.
revision = '6c69768c0d86'
down_revision = '0347f3984f4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=True),
    sa.Column('consult_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consult_id'], ['consultations.consult_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    ### end Alembic commands ###
